### ISSUE TITLE
[Page: Transition and Vibrato]

### ISSUE THREAD

**Issue by JesseJamesJackpot** [claire-west/svstudio-manual#10]
**Describe the problem**
Hi there, Claire. 
Well, it's not really a problem, but a question and an option to clarify.
I'm not sure uploading a picture works, so I'll post a link in case it's not visible.

https://imgur.com/tT8fExT

**In short the question is:**
Do the fade-in and fade-out sections in the diagram correspondent with the left and right sliders in the "Defaults Vibrato" sliders in the voice panel?

**Additional context**
My name is Jesse, I'm a (retired) graphic designer. If you're interested, I could make an updated diagram, to clarify this a bit better. I see an opportunity to create a bigger jump between note A and note B in the diagram to make more space for the middle section about vibrato. Maybe you have additional ideas too to make this diagram better? 

I've only just begun with SynthV (I recently bought the Pro software with Kevin and Solaria voice banks.)
I created this account to be able to send a message, I'm not really familiar with GitHub. So, you can contact me via e-mail if you like: jessecampfens@yahoo.com.

I really appreciate all the effort you made to create this manual. It's very helpful!

Kind regards,
Jesse Campfens

![Transition-Vibrato](https://user-images.githubusercontent.com/127993941/225439822-a3766ecb-d966-4fc6-af4a-3eb6dc13d9f4.jpg)

**Comment by claire-west** [comment]
Oh interesting, I hadn't actually noticed that the terminology changed between the versions of Synthesizer V, but yes those are the same properties, just with different names. I think Dreamtonics probably wanted to avoid people mistaking "fade-in/out" being related to dynamics/loudness.

There might be merit to a diagram remake. The current one was made by Dreamtonics back before the move from SynthV R1 to SynthV Studio, and it's certainly a bit cluttered. Perhaps the best approach would be two separate diagrams; one for transition properties and one for vibrato, so that the topics could be addressed individually in the manual.

I think for improved clarity it would likely be sufficient for me to revise the wording on the page so that readers don't need to look between two images to match things up, but if you wanted to take a stab at a revised diagram I'm certainly open to it.

**Comment by claire-west** [comment]
Looks great! I'll get these into the manual in the next couple days.

How would you like me to credit you for the contribution?

**Comment by JesseJamesJackpot** [comment]
Thanks, I enjoyed making these. You can credit me as Jesse James, but I don't really care that much.
I might make that extra resource soon, I'll show you when it's ready.

**Let me know if there are other things (graphic) to improve...** 
I'm just starting with Synth V, so maybe I'll stumble upon things that could use updating. The one thing that's still mystifying to me is the "instant mode" and what it does exactly. I hear and read contradicting things about turning it on or off etc. I know too little about it yet to ask meaningful questions about it. (I will dive deeper into the manual first.) Thanks again for putting that all together!

As a songwriter producer, I see massive potential for SynthV and voice banks. With all AI developments, this could really skyrocket in the next few years!

BTW: How helpful are the people at SynthV when you have questions for them?
